
server.forward-headers-strategy=framework
# ===============================
# CONFIGURAÇÃO DE BANCO DE DADOS
# ===============================

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# CONFIGURAÇÃO DO JPA / HIBERNATE
# ===============================
# Mostra o SQL gerado no console (útil para ambiente dev)
spring.jpa.show-sql=false

# Formata o SQL no console para facilitar a leitura
spring.jpa.properties.hibernate.format_sql=true

# Estratégia de atualização do banco (update altera as tabelas sem apagar os dados)
spring.jpa.hibernate.ddl-auto=update

server.port=${PORT:8080}