spring.application.name=dscommerce

spring.profiles.active=test
spring.jpa.open-in-view=false

# Configurações do JWT
jwt.secret=073d327d8966fa099516629854ef225642a420b9237666066804cf3b85db0f08
jwt.expiration=86400

logging.level.org.springframework.security=DEBUG